name: Django CMS Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt-get install -yy gettext
          python -m pip install --upgrade pip
          pip install -r test_requirements/django-1.11.txt
      - name: Test
        run: |
          python ./manage.py test
